### PR TITLE
Make it work on latest BLT by moving files around

### PR DESCRIPTION
**Pull request by zatherz**
Moved `common.lua` and `3rdPartyLibrary.lua` to `poco` so that it loads.

### CODE REVIEW

**Comment by zenyr** [comment]
Hey, thanks for the PR, much appreciated! 

I usually merge PR whenever I could confirm it is not breaking anything but I am not using my gaming/modding system right now so I cannot confirm why this change is required to run on BLT just yet. Has something changed on the BLT side since my last commit? 😃

**Comment by zatherz** [comment]
Not sure, I only started modding PD2 recently. The error seems to be with L19 in `common.lua`, which is:
```
Poco._req ('poco/3rdPartyLibrary.lua')
```
I could've also just changed that to `Poco._req ('3rdPartyLibrary.lua')`, but I feel like all of the mod code in one directory instead of half in the root and half in a directory is better.

**Comment by djmattyg007** [comment]
They recently changed to LuaJIT.

**Comment by zenyr** [comment]
Found out the reason I was baffled at the first glance.
There were 2 files missing from last commit for some reason! 😕 
So this PR makes total sense now. Thanks for letting me know!

**Pull request merged**
